version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 588933971286.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=588933971286.dkr.ecr.us-east-1.amazonaws.com//my-docker-repo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build -t 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest .
      - docker tag testcases 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest
      - docker push 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest