version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 588933971286.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo
  build:
    commands:
      - docker build -t 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo .
      - docker tag 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo   
  post_build:
    commands:
      - docker push 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo
      - docker push 588933971286.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo