version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin account-id.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=ecr-uri
  build:
    commands:
      - docker build -t ecr-uri .
      - docker tag ecr-uri ecr-uri:newtag
  post_build:
    commands:
      - docker push ecr-uri
      - docker push ecr-uri
